### ISSUE TITLE
Font awesome do not render. 

### ISSUE THREAD

**Issue by hmendezm** [Wanchai/ngx-capture#10]
Hey guys, nice work in this capture. it is really helpful. I have an SVG with font awesome. And everything in the SVG is rendered except the font awesome. I get a rectangle instead.

See the example below
https://stackblitz.com/edit/ngx-capture-example-s5upqj?file=package.json

Do you have any idea about how I can make this to work?

Best
hmendez

**Comment by Wanchai** [comment]
Thank you. 

What you are experiencing is a limitation of html2canvas:

> Limitations

> All the images that the script uses need to reside under the same origin for it to be able to read them without the assistance of a proxy. Similarly, if you have other canvas elements on the page, which have been tainted with cross-origin content, they will become dirty and no longer readable by html2canvas.

You load FA from another server. Copy the needed files on your project and it will be OK!
