### ISSUE TITLE
Error: InvalidStateError: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### ISSUE THREAD

**Issue by pethugcz** [Wanchai/ngx-capture#18]
When I use ngx-capture on page where exists disabled input using angular material design I'm getting following error:
core.js:5980 ERROR Error: Error: InvalidStateError: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at ngx-capture.js:29
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:28301)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28289)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)

HTML:

```
<div #screen>
  <mat-form-field class="example-full-width">
    <mat-label>Some label (disabled)</mat-label>
    <input matInput disabled value="Some value">
  </mat-form-field>
  <div>
    <button (click)="onClick($event)">Captured</button>
  </div>
</div>
```
TS:
```
import { Component, ViewChild, ElementRef, EventEmitter, OnInit } from '@angular/core';
import { tap } from 'rxjs/operators';
import { NgxCaptureService } from 'ngx-capture';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'test';
  txtdisabled: boolean;

  @ViewChild('screen', { static: true }) screen: any;

  constructor(private captureService: NgxCaptureService) {
    this.txtdisabled = true;
  }

  onClick(e: MouseEvent): void {
    this.captureService.getImage(this.screen.nativeElement, true)
    .pipe(
      tap(img => {
        console.log(img);
      })
    ).subscribe();
  }
}
```
I'm using chrome browser Version 90.0.4430.212 (Official Build) (64-bit).
In case when I use firefox browser it seems that everything is OK.

**Comment by pethugcz** [comment]
I put example on Stackblitz [(https://stackblitz.com/edit/angular-ivy-hwkow5?file=src/app/app.component.html).]() But ... there is angular version 12 and everything is works. My project is in angular version 11. So I will try to migrate on the newest version of angular. And we will see.

**Comment by pethugcz** [comment]
Well ... when I have downloaded source code of example and run it locally I'm getting following error:
Error: InvalidStateError: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at main.js:1
    at e.invoke (polyfills.js:1)
    at Object.onInvoke (main.js:1)
    at e.invoke (polyfills.js:1)
    at t.run (polyfills.js:1)
    at polyfills.js:1
    at e.invokeTask (polyfills.js:1)
    at Object.onInvokeTask (main.js:1)
    at e.invokeTask (polyfills.js:1)
    at t.runTask (polyfills.js:1)
I use chrome browser (Version 91.0.4472.77 (Official Build) (64-bit)).

**Comment by Wanchai** [comment]
Works on Stackblitz.
