### ISSUE TITLE
Would it be possible ngx-capture support another image type than PNG ?

### ISSUE THREAD

**Issue by J2BB** [Wanchai/ngx-capture#2]
Hi,

Congrat' for this amazing lib !! :)

I have a request :
For now, ngx-capture support only PNG image types. 
Would it be possible to add a new settings option allowing to specify image type ?
Some parts of webapps could contain SVG into the DOM for example, and these parts can not be well captured.

In my case, I have an SVG cross icon in my webapp that is minimized when i captured it HTML element.

Thanks,

**Comment by Wanchai** [comment]
Seems related to #9 

Changing the image type won't solve it.
