### ISSUE TITLE
Error: TypeError: undefined is not an object (evaluating 'element.ownerDocument')

### ISSUE THREAD

**Issue by ayubUOL** [Wanchai/ngx-capture#21]
I'm using ngx Capture to take screenshot in Ionic v4 App but it's not working

Version in package json `"ngx-capture": "^0.10.2"`

My code
`this.captureService.getImage(this.screen.nativeElement, true).toPromise().then(img => {
      console.log("NGx Capture -> ", img);
      let encodedURI = encodeURI(img);
    });`

Any help will be helpful. Thank you

**Comment by Wanchai** [comment]
Hi,
I've never worked with Ionic, can you create an example with stackblitz?
What is not working?

Cheers
