### ISSUE TITLE
Angular 12 - ngx-capture image has limited height (image is unintentionally cropped)

### ISSUE THREAD

**Issue by vollukas** [Wanchai/ngx-capture#30]
Hello,
I would like to take a screenshot of an element containing templates or even just a simple static element made from "ul" and "li", but the final image is always cropped after some height of the image.

Wanted:
![image](https://user-images.githubusercontent.com/24632372/134514367-b1e0ed09-722c-4b40-94ae-5727498f4028.png)

Got:
![image](https://user-images.githubusercontent.com/24632372/134514233-2d3e6260-d201-48c0-8d24-ecf7cd8613e0.png)

**Comment by vollukas** [comment]
My html code is like this:
`<ul #screenshot style="list-style-type: none; line-height: 3rem;">
        <li><a routerLink="/task/detail">Task detail</a></li>
        <li><a routerLink="/project/detail">Project detail</a></li>
        <li><a routerLink="/task/edit">Task edit</a></li>
        <li><a routerLink="/project/edit">Project edit</a></li>
        <li><a routerLink="/program/edit">Program edit</a></li>
        <li><a routerLink="/admin/access">Admin access</a></li>
    </ul>`

and my ts like this:
`
  @ViewChild("screenshot", {static: true}) screenshot: any;

makeScreenshot(){
    this.captureService.getImage(this.screenshot.nativeElement, true).subscribe(img => {console.log(img)});
  }
`

**Comment by vollukas** [comment]
My problem was dumb indeed... Your tool is working perfectly! I was just missing the "show more" button in the console to copy the whole base64. My apologies!

**Comment by Wanchai** [comment]
Thanks mate! No problem.
