### ISSUE TITLE
How to catch all screen?

### ISSUE THREAD

**Issue by noamyg** [Wanchai/ngx-capture#33]
Hi,
Would you please provide an example, as for how to capture 100% of the `body`?

The examples provided show how to capture the screen through one of the components. When attaching `#screen` to the lowest-level element (such as the first `div` in `app.component.ts`) you still miss out on your screenshot everything that appends directly to the body, outside of the application root.

Example for stuff that stay out of the screenshot: Toast messages, dialogs, modals, selection boxes that appended to the body for fixed positioning etc.

Thanks

**Comment by Wanchai** [comment]
Hi,
the 'getImage' method on NgxCaptureService takes an HTMLElement as the first parameter. 

So passing `document.body` as the first argument of getImage does the trick.

Cheers

(I'll update the examples)
