### ISSUE TITLE
The capture loses information of the screen that I want to capture

### ISSUE THREAD

**Issue by baarbaracrr** [Wanchai/ngx-capture#40]
I want to make a screenshot that has a leaflet map and I lose the map in the screenshot.

**Comment by nicks258** [comment]
did you found any solution for this?

**Comment by baarbaracrr** [comment]
> did you found any solution for this?

No. The fact that the map is not visible may be due to its size, but I'm not sure. For the moment I capture only the graph.

**Comment by baarbaracrr** [comment]
#2964

**Comment by baarbaracrr** [comment]
https://github.com/niklasvh/html2canvas/issues/2964
