### ISSUE TITLE
not capture whole part of div

### ISSUE THREAD

**Issue by 13hola** [Wanchai/ngx-capture#44]
hello, i cant capture whole area of div

it is capture only visible area,  remaining area is cutting 

any solution..?

For fulll details i already posted on Stackoverflow.

https://stackoverflow.com/questions/75956511/ngx-capture-unable-to-capture-whole-page

**Comment by Wanchai** [comment]
It has been fixed. You should update your version:
https://github.com/Wanchai/ngx-capture/commit/9f3e3d5aadda79b78e5badaf7bbc84229cd90989
