### ISSUE TITLE
unable to capture img with [src]

### ISSUE THREAD

**Issue by vishwalaya** [Wanchai/ngx-capture#45]
Thanks for the library. Liked it.

One minor bug noticed is that it is not capturing img with [src] tag.
<img [src]="dynamicLogo">

**Comment by vishwalaya** [comment]
https://stackblitz.com/edit/ngx-capture-div-angular-4apfbf?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.css

**Comment by Wanchai** [comment]
Try to update to a newer version.
Otherwise it's a limitation from HTML2CANVAS
