### ISSUE TITLE
width and height not in px

### ISSUE THREAD

**Issue by YvesMolina** [Wanchai/ngx-capture#47]
Hi, when launching the project from different computers the crop options I set generate different size images from different computers / browsers.
Nowhere in the doc is it specified what unit of measurement the width and height are in, could you provide it ?
Thanks in advance

**Comment by Wanchai** [comment]
Thanks for pointing that out!
It's fixed in the latest version => https://github.com/Wanchai/ngx-capture/commit/b15cc2d20471fbe1c0e3276a834e99124f382d5b
