### ISSUE TITLE
Image doesn't take into consideration the icons and colors

### ISSUE THREAD

**Issue by nikithaachhini** [Wanchai/ngx-capture#9]
Hi, 

When I used this library the image it gave in base 64 format - skipped the icons

where the actual screenshot looks has the icons as well

**Comment by nikithaachhini** [comment]
button colors and icons are removed

**Comment by nikithaachhini** [comment]
realised that its a issue with html2canvas library itself

https://github.com/niklasvh/html2canvas/issues/432

need to upgrade the html2canvas library version

**Comment by Wanchai** [comment]
Thanks for the input.

You can make a PR if you want.

Cheers.

**Comment by Wanchai** [comment]
Need to see the code but it seems to be the same problem as #10
